#!/usr/bin/env bash
# reset environment variables that could interfere with normal usage
unset GREP_OPTIONS
# put all utility functions here

# make a temporary file
git_extra_mktemp() {
    mktemp -t "$(basename "$0")".XXXXXXX
}

#
# check whether current directory is inside a git repository
#

is_git_repo() {
  git rev-parse --show-toplevel > /dev/null 2>&1
  result=$?
  if test $result != 0; then
    >&2 echo 'Not a git repo!'
    exit $result
  fi
}

is_git_repo
set -e

# Assert there is at least one branch provided
test -z $1 && echo "new branch name required." 1>&2 && exit 1

if [ -z $2 ]; then
    new_branch="$1"
    old_branch="$(git symbolic-ref --short -q HEAD)"
else
    new_branch="$2"
    old_branch="$1"
fi

remote=$(git config branch."$old_branch".remote; true)

git branch -m "$old_branch" "$new_branch"
# check if the branch is tracking a remote branch
if [[ -n "$remote" && "$remote" != "." ]]
then
    git push "$remote" :"$old_branch"
    git push --set-upstream "$remote" "$new_branch"
fi
