#!/bin/bash
#Based on http://blog.lenss.nl/2015/02/composer-install-on-git-clone/
# git config --global alias.clone 'clone --template=[full path]/git-templates'

# Check if a composer.json file is present
function composer_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/composer.json ]; then
        composer install --no-dev
    fi
}

composer_run

# Check if a package.json file is present
function npm_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/package.json ]; then
        npm install
    fi
}

npm_run
