#!/bin/bash
#Based on http://blog.lenss.nl/2015/02/composer-install-on-git-clone/
# git config --global alias.clone 'clone --template=[full path]/git-templates'

# Check if a composer.json file is present
function composer_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/composer.json ]; then
        composer install --no-dev
    fi
}

composer_run

# Check if a package.json file is present
function npm_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/package.json ]; then
        npm install
    fi
}

npm_run

# Check if a bower.json file is present
function bower_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/bower.json ]; then
        bower install
    fi
}

bower_run

# Check if a requirements.txt file is present
function pip_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/requirements.txt ]; then
        pip install -r requirements.txt
    fi
}

pip_run

# Check if a Vagrantfile file is present
function vagrant_run() {
    REPO=$(readlink -m $(dirname .))
    if [ -f $REPO/Vagrantfile ]; then
        vagrant up
    fi
}

vagrant_run
